config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'

  get     'login'  =>  'sessions#new'
  post    'login'  =>  'sessions#create'
  delete  'logout' =>  'sessions#destroy'

  resources :notes
  resources :users

end

app/models/note.rb
class Note < ActiveRecord::Base
    belongs_to :user

    before_save :before_save
    before_destroy :before_destroy
    # http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html
    # better to do this in the controller? hooks are here ...

    private
        def before_destroy
            #TODO enforce ownership before delete
        end

        def before_save
            #TODO enforce ownership before update
        end
end

app/models/user.rb
require 'digest/sha1'


class User < ActiveRecord::Base
    HASH_SALT = 'pepper'

    attr_accessor :new_password

    # TODO email regex? http://stackoverflow.com/q/6325846
    validates :new_password, :presence => true,
        :length => {:maximum => 20, :minimum => 6},
        :confirmation => true

    before_save :before_save

    def self.digest_from_password(plaintext_password)
        return Digest::SHA1.hexdigest(plaintext_password + HASH_SALT)
    end

    private
        def before_save
            self.password_digest = User.digest_from_password(@new_password)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  # TODO enforce user perms ... here?

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all.order('created_at DESC')
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    # should probably just always overwrite
    if current_user and current_user.id  # server-side session if available
      @note.user_id = current_user.id  # more of a last edited by user
    end

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:user_id, :content)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  INVALID_LOGIN = 'Invalid username/password combination'

  def new
  end

  def create
    username = params[:session][:username]
    password = params[:session][:password]

    user = User.find_by(
      username: username,
      password_digest: User.digest_from_password(password)
    )
    if user
      log_in user
      redirect_to user
    else
      flash.now[:danger] = SessionsController::INVALID_LOGIN
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :new_password, :password_digest)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    ANONYMOUS = 'Anonymous'
    # TODO probably a much better place for this \/
    LOGIN_BUTTON_CLASSES = 'ui-btn ui-corner-all ui-btn-inline'\
        ' ui-mini footer-button-left ui-btn-icon-left ui-icon-user'

    def current_user  # nil if invalid id instead of exception
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def logged_in?
        current_user != nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple Notes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div data-role="page">

      <div data-role="header">
      	<h1><%= yield :heading %></h1>
      	<%=
      	  link_to 'New Note', new_note_path,
      	  class: 'ui-btn ui-corner-all ui-btn-inline ui-mini footer-button-left ui-btn-icon-left ui-icon-plus'
      	%>
      	<%= render 'widgets/username_login' %>
      </div>

      <%= yield %>
    </div>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<% content_for :heading do %>
  Notes
<% end %>

<div role="main" class="ui-content">
	<% @notes.each do |note| %>
    <div class="ui-corner-all custom-corners">
      <div class="ui-bar ui-bar-a">
        <h3>
          Note by
          <i><%= note.user ? note.user.username : note.user %></i>
          created on <code><%= note.created_at %></code>
        </h3>
      </div>
      <div class="ui-body ui-body-a">
        <p><%= note.content %></p>
        <p>
          <%= link_to 'Permalink', note %>,
          <%= link_to 'Edit', edit_note_path(note) %>,
          <%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </div>
    </div>
    <br />
  <% end %>
</div>

app/views/notes/new.html.erb
<% content_for :heading do %>
    New Note
<% end %>

<div role="main" class="ui-content">
    <div class="ui-corner-all custom-corners">
        <div class="ui-body ui-body-a">
            <%=
            if logged_in?  # stave off perception of lost data
                render 'form'
            else
                link_to('Login to create notes', login_path,
                    class: SessionsHelper::LOGIN_BUTTON_CLASSES)
            end
            %>
        </div>
    </div>
</div>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @note.user %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :new_password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<% content_for :heading do %>
    New User
<% end %>

<div role="main" class="ui-content">
    <div class="ui-corner-all custom-corners">
        <div class="ui-body ui-body-a">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Log out', logout_path, method: 'delete' %> |
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/widgets/_username_login.html.erb
<%=
    if logged_in?
        link_to(current_user.username, user_path(current_user),
            class: SessionsHelper::LOGIN_BUTTON_CLASSES)
    else
        link_to('Login', login_path,
            class: SessionsHelper::LOGIN_BUTTON_CLASSES)
    end
%>